### ISSUE TITLE
Additional data on season end-point

### ISSUE THREAD

**Issue by davshoward** [samdking/5aside#13]
Given that the season endpoint now is the primary connection, it's important to get the additional data added in order to reduce the client-side computation of static data.

- Add advantaged and disadvantaged object with played, wins, losses, draws
- Add form array e.g. ["Win", "Win", "", "Win", "Loss", "Draw"] (gaps are for no appearance)

**Comment by samdking** [comment]
Done!

**Comment by samdking** [comment]
Although finished this late last night so haven't double checked it.

**Comment by davshoward** [comment]
Looks good - I'll give it a whirl later.
